global using OpenTK.Mathematics;
global using OpenTK.Windowing.Desktop;
global using BinomialHeapLibrary;
global using OpenTK.Graphics.OpenGL4;
global using OpenTK.Windowing.Common;
global using VisualisationBinomialHeap.Models;
global using OpenTK.Windowing.GraphicsLibraryFramework;
global using StbImageSharp;
global using MyMinecraft.Models;